### ISSUE TITLE
Continuous Integration (Travis), Linter(clang-format), and Unit Test

### ISSUE THREAD

**Issue by SoleSun** [UBCFormulaElectric/Consolidated-Firmware#14]
Currently, we have no unit testing. This is _really **really**_ bad. For some examples of what happens when you don't test enough:
- https://en.wikipedia.org/wiki/Mars_Climate_Orbiter
- https://www.wired.com/2014/02/gotofail/
- https://www.theguardian.com/business/2015/may/01/us-aviation-authority-boeing-787-dreamliner-bug-could-cause-loss-of-control
- https://youtu.be/gp_D8r-2hwk?t=53s

There are a few options for C unit testing:
- http://cunit.sourceforge.net/
- https://cmocka.org/
- http://www.throwtheswitch.org/unity/ (especially for embedded software apparently)
- https://libcheck.github.io/check/doc/check_html/index.html (this is the only one I have any personal experience with)

**Comment by thekenu** [comment]
100 years later we have unit testing bless your soul @SoleSun
