### ISSUE TITLE
Support Python 3.8+ in build system

### ISSUE THREAD

**Issue by markomarkusi** [UBCFormulaElectric/Consolidated-Firmware#673]
### Summary
Current Python codebase is  not compatible with Python 3.8+.  Fix scripts to work on all or most versions of Python 3.

**Comment by pasitlaothamatas** [comment]
Ah was this why @alxshev's Gtests were giving weird warnings?

**Comment by markomarkusi** [comment]
Ya I had similar issues when I was setting up on my new laptop, so I just downgrade to Python 3.7.4

**Comment by pasitlaothamatas** [comment]
Very nice
