### ISSUE TITLE
[BMS-41] Implement low pass filter for TS bus voltage

### ISSUE THREAD

**Issue by dash-xa** [UBCFormulaElectric/Consolidated-Firmware#711]
### Summary
BMS-41 says to "Apply a heavy low pass filter on the measured TS (tractive system) bus voltage.". This is currently not being done

**Comment by pasitlaothamatas** [comment]
@Eddy13013 does this need to be done after testing with the HW? Iirc the HW LPF was sufficient right

**Comment by Eddy13013** [comment]
this can be done with hardware if we are unhappy with the voltages we are reading. Tho I had TS voltage readings that were pretty consistent on firmware so I don't think any change is necessary
