### ISSUE TITLE
Make PAPPS or SAPPS count down to be rules compliant.

### ISSUE THREAD

**Issue by gtaharaedmonds** [UBCFormulaElectric/Consolidated-Firmware#737]
### Summary
As per the rules, PAPPS and SAPPS need opposite transfer functions which just means one needs to count up while the other counts down. 

### Deliverables

- [ ] Check the rules to see what is required.

- [ ] Implement this and make sure everything still works.

**Comment by Lucien950** [comment]
can we close?
