### ISSUE TITLE
FSM Testing

### ISSUE THREAD

**Issue by gtaharaedmonds** [UBCFormulaElectric/Consolidated-Firmware#738]
### Summary
General issue for everything that still needs to be tested for FSM. 

### Deliverables
- [x] Test wheel speed
- [x] Test brake pressure + brake plausibility
- [x] Test coolant pump flow
- [x] Test APPs when integrated properly

**Comment by pasitlaothamatas** [comment]
Salutes to General Issue XD (Its a How I Met Your Mother Joke, its very funny, please clap please clap clap please please clap please please please)

**Comment by pasitlaothamatas** [comment]
@kirons96 please spectate and clap

**Comment by kirons96** [comment]
spectates and claps like a boss

**Comment by Lucien950** [comment]
Fixed by #847
