### ISSUE TITLE
Launch Control

### ISSUE THREAD

**Issue by Lucien950** [UBCFormulaElectric/Consolidated-Firmware#969]
### Summary
This is something achievable with the new screen and button layout. A mode can be entered with the screen, causing the accelerator pedal to not deliver torque command. Then, the accelerator can be pressed fully, and the button can be clicked again to launch the car. We can then do math during the launch period to make sure the car accelerates as fast as possible without slip.

Rule T.4.2.12 is the only rule that concerns this feature. 
> ...the integrity of the torque command signal is important at all stages...

**Comment by Lucien950** [comment]
This site looks old, but might demonstrate legality: [Waterloo Launch Control System](https://www.eng.uwaterloo.ca/~d3huang/)

**Comment by gtaharaedmonds** [comment]
Moved to Jira.
