### ISSUE TITLE
Fault display on DIM after shutdow Thruna

### ISSUE THREAD

**Issue by will-chaba** [UBCFormulaElectric/Consolidated-Firmware#984]
### Summary

Have fault display on DIM. Use 7 Segs to display an error code.

This will require enumerating the existing shutdown faults on the car, and having the DIM display them on the 7segs, perhaps flashing through multiple if applicable.

### Deliverables

Faults should display on DIM after BMS shutdown

**Comment by gtaharaedmonds** [comment]
Moved to Jira.
